### ISSUE TITLE
Warning: Error in shinypopupUI: could not find function "shinypopupUI"

### ISSUE THREAD

**Issue by Ericzgg** [jhudsl/papr#6]
Thanks for you advice.  I've already installed the shinysense package, but it still doesn't work. This is the pic. Is there anything wrong？

R version 3.6.1 

![image](https://user-images.githubusercontent.com/16048492/66701941-8a8ba280-ed34-11e9-8488-fa2afd570d67.png)

**Comment by LucyMcGowan** [comment]
Oh shoot - shinysense may have been updated 😬 
ping @nstrayer 👋 we may need to do some updating to keep this up to date with shinysense

**Comment by Ericzgg** [comment]
Oh, I see. That's why. I like your app so much. Meanwhile, why not replace pre-prints with PubMed abstracts? Isn't that more interesting?

**Comment by nstrayer** [comment]
Oh oops. I removed that function because there’s an internal function that does it better called modalPopup. That being said, i did cut a release before updating so it’s relatively easy to get it back. 
```
devtools::install_github(‘nstrayer/shinysense’, ref=‘v1.00’)
```
At some point in the future i should update papr to use the new version.
